const SUPABASE_URL="https://cpfentirkmxzirnhjhgr.supabase.co";const SUPABASE_KEY="sb_publishable_MOt9jcP9HonkGbxQzSZCAA_Z4KpH28U";let accessToken=sessionStorage.getItem('bun_admin_token')||null;let appointments=[];const headers=()=>({apikey:SUPABASE_KEY,Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"});
async function login(email,password){const res=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await res.json();if(!res.ok)throw new Error(data.error_description||data.msg||'Login failed');accessToken=data.access_token;sessionStorage.setItem('bun_admin_token',accessToken);const check=await fetch(`${SUPABASE_URL}/rest/v1/admin_users?id=eq.${data.user.id}&select=id`,{headers:headers()});const admins=await check.json();if(!check.ok||!admins.length){accessToken=null;sessionStorage.removeItem('bun_admin_token');throw new Error('This account is not authorized as a Bun Bun administrator.')}showDashboard();}
function showDashboard(){document.getElementById('loginView').classList.add('hidden');document.getElementById('dashboardView').classList.remove('hidden');loadAppointments()}
document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();const err=document.getElementById('loginError');err.textContent='Signing in...';try{await login(document.getElementById('email').value.trim(),document.getElementById('password').value)}catch(x){err.textContent=x.message}});
async function loadAppointments(){const box=document.getElementById('appointments');box.innerHTML="<div class='message'>Loading appointments...</div>";const res=await fetch(`${SUPABASE_URL}/rest/v1/appointments?select=*&order=appointment_date.asc,appointment_time.asc`,{headers:headers()});if(res.status===401||res.status===403){logout();return}if(!res.ok){box.innerHTML="<div class='message'>Could not load appointments.</div>";return}appointments=await res.json();render()}
function render(){const filter=document.getElementById('filter').value;const search=document.getElementById('search').value.toLowerCase();const rows=appointments.filter(a=>(filter==='all'||a.status===filter)&&(`${a.customer_name} ${a.phone} ${a.service} ${a.location}`.toLowerCase().includes(search)));const count=s=>appointments.filter(a=>a.status===s).length;document.getElementById('total').textContent=appointments.length;document.getElementById('pending').textContent=count('pending');document.getElementById('confirmed').textContent=count('confirmed');document.getElementById('completed').textContent=count('completed');const box=document.getElementById('appointments');if(!rows.length){box.innerHTML="<div class='empty'>No appointments found.</div>";return}box.innerHTML=rows.map(a=>{const date=new Date(a.appointment_date+'T00:00:00').toLocaleDateString('en-ZM',{day:'numeric',month:'short',year:'numeric'});const wa=a.phone.replace(/\D/g,'').replace(/^0/,'260');return `<article class="appointment"><div class="customer"><strong>${escapeHtml(a.customer_name)}</strong><small>${escapeHtml(a.phone)}</small><br><a href="https://wa.me/${wa}" target="_blank" style="color:#167143;font-weight:700">WhatsApp</a></div><div class="meta"><b>${escapeHtml(a.service)}</b><br>${date} • ${escapeHtml((a.appointment_time||'').slice(0,5))}</div><div class="meta">${escapeHtml(a.location)}<br><span class="status ${a.status}">${a.status}</span></div><div class="actions">${a.status==='pending'?`<button onclick="setStatus('${a.id}','confirmed')">Confirm</button>`:''}${a.status!=='completed'&&a.status!=='cancelled'?`<button onclick="setStatus('${a.id}','completed')">Done</button>`:''}${a.status!=='cancelled'?`<button onclick="setStatus('${a.id}','cancelled')">Cancel</button>`:''}</div></article>`}).join('')}
async function setStatus(id,status){const res=await fetch(`${SUPABASE_URL}/rest/v1/appointments?id=eq.${id}`,{method:'PATCH',headers:{...headers(),Prefer:'return=minimal'},body:JSON.stringify({status})});if(res.ok){const a=appointments.find(x=>x.id===id);if(a)a.status=status;render()}else alert('Could not update appointment.')}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function logout(){accessToken=null;sessionStorage.removeItem('bun_admin_token');location.reload()}
document.getElementById('filter').addEventListener('change',render);document.getElementById('search').addEventListener('input',render);document.getElementById('refreshBtn').addEventListener('click',loadAppointments);document.getElementById('logoutBtn').addEventListener('click',logout);if(accessToken)showDashboard();
